import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './components/navbar'
import Footer from './components/footer'
//import stringify from '../middleware/stringify';
import objectify from '../middleware/objectify';

import { API, graphqlOperation } from 'aws-amplify';
import { createTodo, createService, updateService, deleteService } from '../src/graphql/mutations';

export default function Home() {
    const submitService = async (event) => {
      event.preventDefault();
      const stringed = objectify(event.target);
      console.log(stringed);
       try {
        await API.graphql(graphqlOperation(createService, {input: stringed}));
        alert("push complete");
        
       }
        catch (err) {
          console.log(err);
        }

    }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Navbar />
      <main className={styles.main}>
      <form onSubmit={submitService}>
        <div className="mb-3">
            <label  className="form-label">Specialize in:&nbsp;&nbsp;&nbsp;&nbsp;</label>
            <select name="specialize" >
              <option value="">Select</option>
              <option value="Photographer">Photographer</option>
              <option value="Decorator">Decorator</option>
              <option value="Cinematographer">Cinematographer</option>
              <option value="Food seller">Food</option>
          </select>
          </div>
          <div className="mb-3">
            <label  className="form-label">Service name</label>
            <input type="text" className="form-control"  name='serviceName' />
          </div>
          <div className="mb-3">
            <label  className="form-label">Device Name</label>
            <input type="text" className="form-control"  name='lastname' />
          </div>
          <div className="mb-3">
            <label  className="form-label">Years of experience: &nbsp;&nbsp;&nbsp;&nbsp;</label>
            <select name="yearsofexperience" >
              <option value="">Select</option>
              <option value="1-2">1-2</option>
              <option value="3-5">3-5</option>
              <option value="5-10">5-10</option>
              <option value="10-20">10-20</option>
          </select>
          </div>
          <div className="mb-3">
            <label  className="form-label">Email address</label>
            <input type="email" className="form-control" name='email' />
          </div>
          <div className="mb-3">
            <label  className="form-label">Password</label>
            <input type="password" className="form-control" name='password' />
          </div>

          <button type="submit" className="btn btn-primary">Submit</button>
      </form>
      </main>

      <Footer />
    </div>
  )
}
